name: Android CI (Debug APK)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Valida el wrapper para seguridad
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Compila el APK debug
      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace clean assembleDebug

      # Sube el APK compilado con upload-artifact v4
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Pta-debug-apk-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      # (Opcional) Sube logs y salidas por si falla el build
      - name: Upload build outputs and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-${{ github.run_number }}
          path: |
            **/build/reports/**
            **/build/outputs/**
            **/build/intermediates/**
          if-no-files-found: warn
