name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4️⃣ Configurar SDK Android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2

      # 5️⃣ Construir APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 6️⃣ Subir APK como artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pta-filtrado-APK
          path: app/build/outputs/apk/debug/app-debug.apk
