name: Build Android Full

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk: 25.2.9519653

      # 5️⃣ Grant execute permission to gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 6️⃣ Copy drawable images to runner (asegura recursos)
      - name: Copy drawable images
        run: |
          mkdir -p $GITHUB_WORKSPACE/app/src/main/res/drawable
          cp -r $GITHUB_WORKSPACE/drawable/* $GITHUB_WORKSPACE/app/src/main/res/drawable/

      # 7️⃣ Clean and build APK
      - name: Clean and assemble APK
        run: ./gradlew clean assembleDebug

      # 8️⃣ Upload APK artifact (v4)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pta-filtrado-APK
          path: app/build/outputs/apk/debug/app-debug.apk
